#!/usr/bin/env python3
"""SAFE unified build — Food Safety Practice Test AU.

Runs the safe generators in order and regenerates sitemap.xml from the single
source of truth (SITEMAP_URLS.py). It NEVER writes to the manual pages:
  index.html, guide.html, temperature-danger-zone-checker.html,
  bookmarks.html, progress.html

It also NEVER calls tools/build_site.py (which would overwrite manual pages).

Run:  python3 tools/build_all_safe.py
"""
import runpy, hashlib, pathlib, sys, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
sys.path.insert(0, str(TOOLS))
import SITEMAP_URLS as S  # single source of truth

# Pages that must never be regenerated by this pipeline.
MANUAL = ["index.html", "guide.html", "temperature-danger-zone-checker.html",
          "bookmarks.html", "progress.html"]

# Generators to run, in order. None of these write to MANUAL pages.
GENERATORS = [
    "build_blog_posts.py",
    "build_jobs.py",
    "build_keyword_pages.py",
    "build_topics_only.py",
]


def md5(path):
    p = ROOT / path
    return hashlib.md5(p.read_bytes()).hexdigest() if p.exists() else None


BYLINE = ('<p class="byline" data-byline style="color:var(--muted);font-size:.85rem;border-top:1px solid var(--line);'
          'margin-top:22px;padding-top:14px;">Written and reviewed by the Food Safety Practice AU editorial team. '
          'Last reviewed June 2026. Based on the <a href="https://www.foodstandards.gov.au/" target="_blank" rel="noopener">'
          'Food Standards Code (FSANZ)</a> and Australian state/territory food authorities. General guidance only &mdash; '
          'not official certification.</p>\n        ')
BYLINE_EXCLUDE = {"index.html", "bookmarks.html", "progress.html", "terms.html", "legal.html", "blog/index.html"}


def apply_bylines():
    """Ensure every content page has the E-E-A-T 'reviewed/last-updated/sources' byline.
    Idempotent; re-applies after generators regenerate pages."""
    import glob
    files = [f for f in glob.glob("*.html", root_dir=ROOT) if f not in BYLINE_EXCLUDE]
    files += [f for f in glob.glob("blog/**/index.html", root_dir=ROOT, recursive=True) if f != "blog/index.html"]
    n = 0
    for rel in files:
        p = ROOT / rel
        h = p.read_text(encoding="utf-8")
        if "data-byline" in h:
            continue
        i = h.rfind("</article>")
        if i < 0:
            continue
        p.write_text(h[:i] + BYLINE + h[i:], encoding="utf-8")
        n += 1
    return n


def write_sitemap():
    today = "2026-06-10"
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url in S.urls():
        lines.append(f'  <url>\n    <loc>{url}</loc>\n    <lastmod>{today}</lastmod>\n  </url>')
    lines.append('</urlset>')
    (ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(S.PATHS)


def main():
    print("== SAFE BUILD ==")
    before = {f: md5(f) for f in MANUAL}

    for g in GENERATORS:
        print(f"\n-- running {g} --")
        runpy.run_path(str(TOOLS / g), run_name="__main__")

    b = apply_bylines()
    print(f"\nbylines ensured on content pages (+{b} added)")

    n = write_sitemap()
    print(f"sitemap.xml regenerated from SITEMAP_URLS.py ({n} URLs)")

    # Safety assertion: manual pages must be byte-identical.
    after = {f: md5(f) for f in MANUAL}
    changed = [f for f in MANUAL if before[f] != after[f]]
    if changed:
        print("\n!! SAFETY FAILURE — manual pages were modified:", changed)
        sys.exit(1)
    print("\nOK — manual pages unchanged:", ", ".join(MANUAL))
    print("Done.")


if __name__ == "__main__":
    main()
